### ISSUE TITLE
Suggest MIPI as PA enable signal to execute wlan devm test

### ISSUE THREAD

**Issue by hackrfmo2015** [NISystemsEngineering/rfic-reference-design-libraries-labview#6]
I run Digital Dynamic PAEN\main.vi, and found VST5840 PFI0 can export a toggle signal with TDD RF burst on. But it can't trigger PXI-E 6570 to export the enable/disable signal. Also it can't support when a mipi device to do Devm test.
Hope you can fix it soon!
Thank you!

**Comment by mdwhitten** [comment]
Hi @hackrfmo2015 ,

I apologize, somehow this issue never made it to my inbox. Not sure what happened! I don't know if you are still interested/working on this. However, the example mentioned above can indeed be used for triggering the 6570 (albeit in a non-ideal fashion).

The example includes .digipat files that reference the **Digital Wait** pattern. This pattern waits in a loop for a pin to change state. When the PFI0 connection on the 5840 is connected to the pin utilized by this pattern, the 6570 will exit the **Digital Wait** pattern exactly 830 ns later. Since this is a known delay, this can be leveraged in order to "trigger" the 6570 in this way, which the example pattern shows. This has been successfully used to do dEVM testing with an RFFE MIPI DUT.

Please let me know if I can clarify further how to utilize the example to witness this result.
