### ISSUE TITLE
Proposal to enable updating existing reference for waveforms

### ISSUE THREAD

**Issue by smooresni** [NISystemsEngineering/rfic-reference-design-libraries-labview#69]
![image](https://user-images.githubusercontent.com/51342134/69090828-ba525800-0a0e-11ea-91cd-e344e6d48b5b.png)

![image](https://user-images.githubusercontent.com/51342134/69091109-3ba9ea80-0a0f-11ea-9ae6-0ed0cc667aaa.png)

This enables:
![image](https://user-images.githubusercontent.com/51342134/69091157-5714f580-0a0f-11ea-9ea7-094ab4176d2a.png)

**Comment by mdwhitten** [comment]
This seems like a problem, though. Isn't the whole point that we should leave intact the original reference? Since that original reference waveform could still be used for AMPM measurements, for example? We wouldn't want to end up with a waveform struct representing the reference waveform where the data pointer inside of it pointed to the CFR waveform.

**Comment by smooresni** [comment]
Yes appears my attempt to be clever would indeed introduce undesirable behavior. Good call.
